# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: wwx's BLOG
subtitle: 'Be brave'
description: ''
keywords:
author: W WX
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://gitwwx.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: prismjs
# highlight:
  # enable: false
  # line_number: true
  # auto_detect: false
  # tab_replace: ''
  # wrap: true
  # hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''

# 代码块相关
code:
  lang: true # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: false # 代码块是否可以收缩
  break: false # 代码是否折行  

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery

search:
  path: search.xml
  field: post

permalink_pinyin:
  enable: true
  separator: '-' # default: '-'  

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/gitwwx/gitwwx.github.io.git
  branch: main

# Theme Customize
theme_config:
  favicon: /favicon.png
  logo: /medias/logo2.png
  # The configurations of the second line of home banner
  # icon/button will not show up if you leave the corresponding socialLink empty
  # 首页 banner 中的第二行个人信息配置，留空即不启用
  socialLink:
    github:  https://github.com/gitwwx
    email: 1791445436@qq.com
    facebook: # https://www.facebook.com/xxx
    twitter: # https://twitter.com/xxx
    qq: 1791445436
    weibo: # https://weibo.com/xxx
    zhihu: # https://www.zhihu.com/xxx
    rss: false # true、false
  reward:
    enable: true
    title: 你的赏识是我前进的动力
    wechat: /medias/reward/wechat.jpeg
    alipay: /medias/reward/alipay.jpeg  
  # If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.
  # 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.  
  myProjects:
    enable: false  
  mySkills:
    enable: false  
  busuanziStatistics:
    enable: false 
    totalTraffic: false # 总访问量
    totalNumberOfvisitors: false # 总人次 
  baiduPush: false  
  indexbtn:
    enable: false
  # Whether to display fork me on github icon and link, default true, You can change it to your repo address
  # 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.  
  githubLink:
    enable: false  
  # sharejs文章分享模块.
  # 支持顺序，可选项目为twitter, facebook, google, qq, qzone, wechat, weibo, douban, linkedin.
  sharejs:
    enable: true
    sites: qq,wechat
  # index page dream text,
  # 配置首页显示"梦想"的语句.
  dream:
    enable: true
    showTitle: true
    title: 加油
    text: 世界上只有一种真正的英雄主义，那就是在认清生活真相之后依然热爱生活。——罗曼·罗兰  